name: Deploy Dev Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/dev/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Optional auto-apply (you can comment this out at first)
      - name: Terraform Apply
        run: terraform apply -auto-approve
