#Trigger CI
name: Deploy Dev Terraform

on:
  push:
    branches:
      - main
   

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}


    defaults:
      run:
        working-directory: terraform/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
      - name: Debug region presence (safe)
        run: |
          echo "AWS_DEFAULT_REGION is set? -> ${{ secrets.AWS_DEFAULT_REGION != '' }}"
