name: Deploy Prod Terraform

on:
  push:
    branches: [ "main" ]
    paths:
      - "terraform/prod/**"
      - ".github/workflows/deploy-prod.yml"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: prod

    defaults:
      run:
        working-directory: terraform/prod

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.PROD_AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_bucket_name: ${{ secrets.PROD_BUCKET_NAME }}
          TF_VAR_aws_region: ${{ secrets.PROD_AWS_DEFAULT_REGION }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_bucket_name: ${{ secrets.PROD_BUCKET_NAME }}
          TF_VAR_aws_region: ${{ secrets.PROD_AWS_DEFAULT_REGION }}
